{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-datasource",
    "version": "2.18.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-datasource-2.18.2.aar",
          "url": "exoplayer-datasource-2.18.2.aar",
          "size": 139942,
          "sha512": "d4e7253c301bcea3b3f4cd7ffe3550d10272fc27a27571ab3496ceda2fe532ad3aaee96b000ea8b154337d6e78e7dd1de975ee445513ee3bdb0171059759a1a2",
          "sha256": "ae6246b4c71f7764075c91b1b5d53942f93d449147c77eb19ec538f6282b03f5",
          "sha1": "ae8d75fd9254515883e78c3eb76883eb2e0d04b9",
          "md5": "057761263e3e5eced1f37c8b88b5d4be"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-database",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-datasource-2.18.2.aar",
          "url": "exoplayer-datasource-2.18.2.aar",
          "size": 139942,
          "sha512": "d4e7253c301bcea3b3f4cd7ffe3550d10272fc27a27571ab3496ceda2fe532ad3aaee96b000ea8b154337d6e78e7dd1de975ee445513ee3bdb0171059759a1a2",
          "sha256": "ae6246b4c71f7764075c91b1b5d53942f93d449147c77eb19ec538f6282b03f5",
          "sha1": "ae8d75fd9254515883e78c3eb76883eb2e0d04b9",
          "md5": "057761263e3e5eced1f37c8b88b5d4be"
        }
      ]
    }
  ]
}
