{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-hls",
    "version": "2.18.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-hls-2.18.2.aar",
          "url": "exoplayer-hls-2.18.2.aar",
          "size": 159388,
          "sha512": "4b819c4a67d7fd8e9e2f8dacb54006f120d1680e1476170623635375bab795868dc51ee80639ec173e580c62db6a08214f156d2e7b86bf1dbc1a2e21b94520ae",
          "sha256": "6b10d81d4c2c3c4adefd7e9a7580e1b5098751c3d50142147a67535a7c70dd5c",
          "sha1": "42217b9d46e78a64b032a6d9868cb503ebe596c2",
          "md5": "8935cdfa6349a7b64d251d4f95543ef3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-hls-2.18.2.aar",
          "url": "exoplayer-hls-2.18.2.aar",
          "size": 159388,
          "sha512": "4b819c4a67d7fd8e9e2f8dacb54006f120d1680e1476170623635375bab795868dc51ee80639ec173e580c62db6a08214f156d2e7b86bf1dbc1a2e21b94520ae",
          "sha256": "6b10d81d4c2c3c4adefd7e9a7580e1b5098751c3d50142147a67535a7c70dd5c",
          "sha1": "42217b9d46e78a64b032a6d9868cb503ebe596c2",
          "md5": "8935cdfa6349a7b64d251d4f95543ef3"
        }
      ]
    }
  ]
}
