{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "6.7.1",
      "buildId" : "4pwnwrvt3vgwpb7radkvp6tjgm"
    }
  },
  "component" : {
    "group" : "com.github.ByteHamster",
    "module" : "SearchPreference",
    "version" : "v2.3.0",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "releaseApiPublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-api"
    },
    "files" : [ {
      "name" : "SearchPreference-v2.3.0.aar",
      "url" : "SearchPreference-v2.3.0.aar",
      "size" : 66320,
      "sha512" : "7af168b119432f10c5f4c7c894cc357c843549c3facd819b2d3022fb5b987ae82ad27448259f6bbca5486c06066d3c96791f1ebe3d6eba9827cbc083d6f1d1be",
      "sha256" : "c843f681c7c28e772e50cb6935ab535f585e2e4ed2efa750d55538c65a916f4f",
      "sha1" : "d84db04b7406d4020dc464c27b3b41e7a4a45d0c",
      "md5" : "30a10484d15bf7259ab79d863ca7213f"
    } ]
  }, {
    "name" : "releaseRuntimePublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "androidx.appcompat",
      "module" : "appcompat",
      "version" : {
        "requires" : "1.2.0"
      }
    }, {
      "group" : "androidx.cardview",
      "module" : "cardview",
      "version" : {
        "requires" : "1.0.0"
      }
    }, {
      "group" : "androidx.recyclerview",
      "module" : "recyclerview",
      "version" : {
        "requires" : "1.1.0"
      }
    }, {
      "group" : "androidx.preference",
      "module" : "preference",
      "version" : {
        "requires" : "1.1.1"
      }
    }, {
      "group" : "org.apache.commons",
      "module" : "commons-text",
      "version" : {
        "requires" : "1.3"
      }
    } ],
    "files" : [ {
      "name" : "SearchPreference-v2.3.0.aar",
      "url" : "SearchPreference-v2.3.0.aar",
      "size" : 66320,
      "sha512" : "7af168b119432f10c5f4c7c894cc357c843549c3facd819b2d3022fb5b987ae82ad27448259f6bbca5486c06066d3c96791f1ebe3d6eba9827cbc083d6f1d1be",
      "sha256" : "c843f681c7c28e772e50cb6935ab535f585e2e4ed2efa750d55538c65a916f4f",
      "sha1" : "d84db04b7406d4020dc464c27b3b41e7a4a45d0c",
      "md5" : "30a10484d15bf7259ab79d863ca7213f"
    } ]
  } ]
}