{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-decoder",
    "version": "2.18.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-decoder-2.18.2.aar",
          "url": "exoplayer-decoder-2.18.2.aar",
          "size": 17072,
          "sha512": "d1d812f7fb709f9b0bb08b04436996cc7bfcd1897174c2885175aae3af475e80d090e6ca7f94aeeb3306a996a60f4fb25188bed762d828194cbb8ee6ba4f9cb5",
          "sha256": "0457a13698b934190871a2b6b376668f252dbd216ef7106196a062bfd2089b2e",
          "sha1": "f0bb9c6e6790a5beb2117dad45dc584b8e0dcf32",
          "md5": "cdda7d5c6d813afd959f00df02396366"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-decoder-2.18.2.aar",
          "url": "exoplayer-decoder-2.18.2.aar",
          "size": 17072,
          "sha512": "d1d812f7fb709f9b0bb08b04436996cc7bfcd1897174c2885175aae3af475e80d090e6ca7f94aeeb3306a996a60f4fb25188bed762d828194cbb8ee6ba4f9cb5",
          "sha256": "0457a13698b934190871a2b6b376668f252dbd216ef7106196a062bfd2089b2e",
          "sha1": "f0bb9c6e6790a5beb2117dad45dc584b8e0dcf32",
          "md5": "cdda7d5c6d813afd959f00df02396366"
        }
      ]
    }
  ]
}
