{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-common",
    "version": "2.18.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "exoplayer-common-2.18.2.aar",
          "url": "exoplayer-common-2.18.2.aar",
          "size": 370812,
          "sha512": "0ff385a8194ca568464dff398c63c3739201bfd23cb61eb31e955fd63036d116c09f5b70608bf722d664923e290a3db3127918d14d44ad86a32dec9f636aaa7b",
          "sha256": "a240f2b4104089e4567c1433d8955e4dc846b8a437584082ba4681a58da9141d",
          "sha1": "c4c7d5e19f5f1eeddac5a8dc4e004cd2cc91660b",
          "md5": "932912dd1c483815fdee8080d1777ac5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "exoplayer-common-2.18.2.aar",
          "url": "exoplayer-common-2.18.2.aar",
          "size": 370812,
          "sha512": "0ff385a8194ca568464dff398c63c3739201bfd23cb61eb31e955fd63036d116c09f5b70608bf722d664923e290a3db3127918d14d44ad86a32dec9f636aaa7b",
          "sha256": "a240f2b4104089e4567c1433d8955e4dc846b8a437584082ba4681a58da9141d",
          "sha1": "c4c7d5e19f5f1eeddac5a8dc4e004cd2cc91660b",
          "md5": "932912dd1c483815fdee8080d1777ac5"
        }
      ]
    }
  ]
}
