{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.mediarouter",
    "module": "mediarouter",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mediarouter-1.3.1.aar",
          "url": "mediarouter-1.3.1.aar",
          "size": 744156,
          "sha512": "e887b62d7b2b753880ae28755d4a3ab4edd74ba1ead59a57b9a4a47ed7bdf4f414b2184896813eb6e454f2efa201d9fb6f67c01294fa1b0082ac3b905646c779",
          "sha256": "821089bb1bf68809ef7027a3959c509c45d6b51fd10f0c6f8005bdfb00a914fe",
          "sha1": "9c4446324b43008404bb6caba5b09e8726ca64a8",
          "md5": "90526ac4144fc777cbfafaf0bf496064"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mediarouter-1.3.1.aar",
          "url": "mediarouter-1.3.1.aar",
          "size": 744156,
          "sha512": "e887b62d7b2b753880ae28755d4a3ab4edd74ba1ead59a57b9a4a47ed7bdf4f414b2184896813eb6e454f2efa201d9fb6f67c01294fa1b0082ac3b905646c779",
          "sha256": "821089bb1bf68809ef7027a3959c509c45d6b51fd10f0c6f8005bdfb00a914fe",
          "sha1": "9c4446324b43008404bb6caba5b09e8726ca64a8",
          "md5": "90526ac4144fc777cbfafaf0bf496064"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mediarouter-1.3.1-sources.jar",
          "url": "mediarouter-1.3.1-sources.jar",
          "size": 198254,
          "sha512": "e669699fabc9d870afee42c95866f129d5766532d38885adbef3ae966458675ed8a9f75c746551745d6ee22b112a21cdb115ee4c1d2a9d1c2dce9325e8bca4cf",
          "sha256": "7e29ba538fff15798cec23a87b16239d37218b4990e8dbc86546c0d908ec0bd2",
          "sha1": "9a085c65713c030448c55190da3b424bb7fb4ee9",
          "md5": "97172e5ba0cda8b4643df2b06d50ba7e"
        }
      ]
    }
  ]
}
